name: Repository Dispatch
on:
  repository_dispatch:
    types: [rubocop-linter-action-test]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: delete old files if needed
        run: |
          find . -name ".github/workflow_template/test.yml" -delete
          find . -name ".github/workflow_template/rubocop.yml" -delete
      - name: create new file
        run: |
          sed 's/changemepls/${{ github.event.client_payload.sha }}/g' .github/workflow_template/test_template.yml > .github/workflows/test.yml
          sed 's/changemepls/${{ github.event.client_payload.sha }}/g' .github/workflow_template/rubocop_template.yml > .github/workflows/rubocop.yml
      - name: Commit files
        run: |
          git config --local user.email "andrewmcodes@protonmail.com"
          git config --local user.name "Andrew Mason"
          git switch -c ${{ github.event.client_payload.sha }}
          git add .
          git commit -m "test ${{ github.event.client_payload.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
