name: Rubocop

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@config-updates
      with:
        action_config: '.github/config/rubocop_linter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
