name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@c5f00ee5c13cdf33e411227a38c9ab1dd636ea38
      with:
        action_config: '.github/config/rubocop_linter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
