name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@fc5e6b2c02628d55e41baa53ffa552f9e918bf83
      with:
        action_config: '.github/config/rubocop_linter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
