name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@d63cd065df651d6a2fe81871b9983f5cc049859f
      with:
        action_config: '.github/config/rubocop_linter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
