name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@b119203b9411244c38fbc7f3096ba6dd7a13e19a
      with:
        action_config_path: '.github/config/rubocop_linter_config.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
