name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@ad1b067d3cf2aa595947f9a04622f95c169a502e
      with:
        action_config: '.github/config/rubocop_linter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
