name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@11bed23bf629651c55f7df3222a9d2c7181971ba
      with:
        action_config_path: '.github/config/rubocop_linter_config.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
