name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@a470804bc69c5dbad9861c307f172bb55054fd74
      with:
        action_config: '.github/config/rubocop_linter_config.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
