on: issue_comment
name: Issue Comments
jobs:
  check_comments:
    name: Check comments for /rubocop
      steps:
        - name: Check for Command
          id: command
          uses: xt0rted/slash-command-action@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            command: test
            reaction: "true"
            reaction-type: "eyes"
            allow-edits: "false"
            permission-level: admin
        - name: Act on the command
          uses: andrewmcodes/rubocop-linter-action@config-updates
          with:
            action_config: '.github/config/rubocop_linter.yml'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
