name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@ae662783c2e92663b69f4e588eae62f876526f0a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@ae662783c2e92663b69f4e588eae62f876526f0a
        with:
          action_config: '.github/config/rubocop_linter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
