name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@60c9e83677470c34f9ec16edf24b1125a29b41c1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@60c9e83677470c34f9ec16edf24b1125a29b41c1
        with:
          action_config: '.github/config/rubocop_linter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
