name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@c0d4cde7115d5cbefae6c7dd5b35c0512fdd6902
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@c0d4cde7115d5cbefae6c7dd5b35c0512fdd6902
        with:
          action_config: '.github/config/rubocop_linter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
