name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@cd0a4d5f08003e9b86e39cd2a4aada0cafbdf960
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@cd0a4d5f08003e9b86e39cd2a4aada0cafbdf960
        with:
          action_config_path: '.github/config/rubocop_linter_config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
