name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'tickgit-10'
        uses: andrewmcodes/tickgit-action@build
        with:
          version: latest
