name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@2836711edbc412bef7361dd96312adc4f606ab9c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@2836711edbc412bef7361dd96312adc4f606ab9c
        with:
          action_config: '.github/config/rubocop_linter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
