name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@1cd5e9ccc2952e51fd0abd92aed57593052fc459
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@1cd5e9ccc2952e51fd0abd92aed57593052fc459
        with:
          action_config_path: '.github/config/rubocop_linter_config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
