name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@10c99a3c0c3586ccb3e1bfa8375f31225e43c46b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@10c99a3c0c3586ccb3e1bfa8375f31225e43c46b
        with:
          action_config_path: '.github/config/rubocop_linter_config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
