name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@948a934c490d2e802e5a6a0bf40189a1105c819e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@948a934c490d2e802e5a6a0bf40189a1105c819e
        with:
          action_config_path: '.github/config/rubocop_linter_config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
