name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/rubocop-linter-action@c5d1a50416913d8b2afaa6651d6663915e7dd243
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/rubocop-linter-action@c5d1a50416913d8b2afaa6651d6663915e7dd243
        with:
          action_config: '.github/config/rubocop_linter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
